apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: workzen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ajeetkrup1234/workzen-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/workzen"
