apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: workzen
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32000
  selector:
    app: prometheus
